### PR TITLE
add js migration file for update observatory procedure

### PR DESCRIPTION
**Pull request by Datayama38**

### CODE REVIEW

**Comment by jonathanfallon** [comment]
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit dda14527f1b53e04c61811c68dd1ab24196f3759. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=63ebd539a53ecd331737f524&branchName=2261,fix/migrations_update_procedures_observatory)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`lerna run build`](https://cloud.nx.app/runs/xUeO0F4M3d)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

**Comment by jonathanfallon** [comment]
Il n'y a pas de fichiers de migration en SQL ?

**Review by jonathanfallon — COMMENTED** [review]
Il n'y a pas de fichiers de migration en SQL ?

**Comment by Datayama38** [comment]
Ils sont déjà là, j'avais juste oublié le js

**Review by P3rceval — APPROVED** [review]

**Pull request merged**
